import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SideBar from "./_components/Side-Bar/SideBar";



import { Toaster } from "@/components/ui/sonner"


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="">
          {/* Sidebar on the left */}
          <aside className="">
            <SideBar />
          </aside>

          {/* Main content on the right */}
          <main className="flex-1 section_space overflow-auto bg-zinc-800">
            
            {children}
<Toaster
          position="top-center"
        />
          </main>
        </div>
      </body>
    </html>
  );
}